"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 2.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the settings like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'p)d1@8z3ynm7duiu_@nc$j+!x*o(naye8e35g%^xlg-@yha_y%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',

    'backend',
    'client',
    'rest',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                'project.context_processor.options',
                'project.context_processor.site_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, '../db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
STATIC_ROOT = os.path.join(BASE_DIR, 'static')


# CUSTOM SETTINGS
SITE_OPTIONS = {
    # reviews
    'review': {
        'send': False,
        'see': True,
    },

    # common
    'search': True,
    'sales': True,

    # category
    'category': {
        'rating': False,
    },

    # product
    'product': {
        'price': False,
        'rating': False,
        'related': True,
    },

    # shop page
    'sort': False,
    'pagination': False,
    'filter': {
        'price': False,
        'color': False,
        'brand': False,
    },

    # customer
    'login': False,
    'order': True,
    'wish': False,
    'cart': False,

    # contact
    'contact_map': False,

    # social network
    'social': {
        'facebook': True,
        'pinterest': False,
        'twitter': False,
        'youtube': True,
        'instagram': True,
        'googleplus': True,
        'tumblr': False,
    },
    'social_images': True,

    # payments:
    'payment': {
        'mastercard': True,
        'paypal': False,
        'american': False,
        'visa': True,
    },

}

SITE_SETTINGS = {
    'name_site': 'Modul-Lux Site',
    'phone': '+380 56 123 4578',
    'email': 'modul-lux@gmail.com',
    'address': 'г.Днепр, ул.Ленина, 1, ТЦ "СитиМебель"',
    'work_hours': 'Понедельник-Суббота 09:00–19:00',

    'support': {
        'phone': '+380 56 123 4578',
        'email': 'service_support@gmail.com',
        'address': 'г.Днепр, ул.Осенняя, 1',
        'work_hours': 'Понедельник-Суббота 11:00–17:00',

    },

    'online': {
        'phone': '+380 56 123 4578',
        'email': 'online_support@gmail.com',
    }
}