# Generated by Django 2.1.2 on 2018-10-29 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientMessageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя клиента')),
                ('email', models.CharField(max_length=255, verbose_name='Почтовый адрес клиента')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('is_done', models.BooleanField(default=False, verbose_name='Обработано')),
            ],
        ),
    ]
