# Generated by Django 2.1.2 on 2018-10-12 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
            ],
            options={
                'verbose_name_plural': 'Категории',
                'verbose_name': 'Категория',
            },
        ),
        migrations.CreateModel(
            name='CategoryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение категории')),
                ('is_default', models.BooleanField(default=False, verbose_name='Изображение по-умолчанию')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='backend.Category')),
            ],
            options={
                'verbose_name_plural': 'Изображения мебели',
                'verbose_name': 'Изображение мебели',
            },
        ),
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='furnitures', to='backend.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name_plural': 'Мебели',
                'verbose_name': 'Мебель',
            },
        ),
        migrations.CreateModel(
            name='FurnitureImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение мебели')),
                ('is_default', models.BooleanField(default=False, verbose_name='Изображение по-умолчанию')),
                ('furniture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='backend.Furniture')),
            ],
            options={
                'verbose_name_plural': 'Изображения мебели',
                'verbose_name': 'Изображение мебели',
            },
        ),
    ]
